### PR TITLE
Updated !gif to use giphy

### PR DESCRIPTION
**Pull request by TetraEtc**
Uses safygiphy to search the giphy library. Returns better quality gifes

Safygiphy located here: https://github.com/TetraEtc/safygiphy

### CODE REVIEW

**Comment by llimllib** [comment]
I actually prefer gogle's gifs. Maybe you could add a !giphy plugin and some tests?

**Comment by TetraEtc** [comment]
There you go. Replaced the !gif, added !giphy, and some basic tests. Also
changed the error handling of !giphy as well.

**Comment by TetraEtc** [comment]
I believe I should have fixed the errors causing the tests to fail

**Comment by TetraEtc** [comment]
The issues were with the API wrapper, not with the commit, so I can't trigger another set of tests. Can you manually cycle them again?

**Comment by llimllib** [comment]
Sorry, just haven't had time to maintain it lately. Will get to it tonight.

**Comment by llimllib** [comment]
OK, the errors look like your safygiphy library doesn't support python 2.6 or python 3.4. Can you update it to support those python versions?

**Comment by TetraEtc** [comment]
Working on it. 

2.6 will be easy to fix, 3.4 will need a little bit of extra work though.

**Pull request closed without merging**
