### PR TITLE
handle bot messages

### PR DESCRIPTION
**Pull request by llimllib**

### CODE REVIEW

**Comment by TetraEtc** [comment]
Just out of curiosity - This adds in the ability to respond to bots? (Potentially differently to how you reply to a person?)

**Comment by llimllib** [comment]
The ability was already there, this just makes the default plugins respond to bot messages by default

**Comment by llimllib** [comment]
I still have to merge your PR! Sorry

**Comment by TetraEtc** [comment]
All good :)

I wasn't even aware that `on_bot_message` was a thing! That could be useful

**Pull request merged**
