### PR TITLE
Fix regex for image / gif scraping.

### PR DESCRIPTION
**Pull request by fenwar**

### CODE REVIEW

**Comment by llimllib** [comment]
Thanks!  Will review

**Comment by fenwar** [comment]
I should've run the tests, sorry. This fails but I guess the test fixture
needs updating to match the new format of the image search results. IDK if
I have time to figure out the fixture formatjust yet.

**Comment by llimllib** [comment]
np, I will try to fix that

**Comment by llimllib** [comment]
FTR, the process was:

* `rm test/fixtures/image_* test/fixtures/gif_*` the `make test` (pytest generates the updated fixtures automatically)
* insert a print statement in gif.py and image.py to print all the possible images/gifs
* insert that list into the test case

(Not saying you should have known how to do this! Just leaving it in case it's useful someday... to myself maybe)

Thanks for the contribution!

**Comment by llimllib** [comment]
released 7.1.0 with the updated plugins

**Pull request merged**
