### PR TITLE
Adding Urban Dictionary Plugin - Updated Readme

### PR DESCRIPTION
**Pull request by TetraEtc**
This adds a new plugin, for Urban Dictionary.

!urban <term>

Returns the most popular definition, as well as the example for that definition.

### CODE REVIEW

**Comment by TetraEtc** [comment]
Grr - The encoding is causing me headaches. Potentially remove .encode from searchterm, replace with decode at this point?

**Comment by TetraEtc** [comment]
Sweet... Passed tests. If statements are useful

**Comment by TetraEtc** [comment]
All good! Whenever you get around to it :smile:

**Comment by llimllib** [comment]
Committed in https://github.com/llimllib/limbo/commit/dbb3c85b529ca3917362badd90868e593328946e

**Comment by TetraEtc** [comment]
Thanks!

I think I may have fixed some of the issues in a private repo (Quotes etc) but never got around to adding it into this repo.

**Pull request closed without merging**
